### ISSUE TITLE
Acceptor image loading issue

### ISSUE THREAD

**Issue by dougkelly88** [openmicroscopy/Imperial-FLIMfit#109]
Acceptor images cannot be loaded, error below. Running on Windows Server 2012, FLIMfit 4.7.2 *and* 4.6.6. 

Starting FLIMfit...
Error using Settings
Undefined function or variable 'matlab.internal.getSettingsRoot'.

Error in iptgetpref (line 22)

Error in medfilt2>hUseIPPL (line 176)

Error in medfilt2 (line 58)

Error in flim_data_series/load_acceptor_images (line 116)

Error in front_end_menu_controller/menu_file_load_acceptor_callback (line 584)

Error in front_end_menu_controller/set_callbacks/@(varargin)obj.menu_file_load_a
cceptor_callback(varargin{:})

Error using waitfor
Error while evaluating uimenu Callback

**Comment by imunro** [comment]
Solved by move to 2014b or removal of .prj files. See https://github.com/openmicroscopy/Imperial-FLIMfit/commit/b93a5c8d0484fac90947721909ffe8e3e6abe9c4
