### ISSUE TITLE
making an average background is not possible with an ome.tiff stack

### ISSUE THREAD

**Issue by FLIMinator** [openmicroscopy/Imperial-FLIMfit#116]

**Comment by imunro** [comment]
Can I confirm? You want to be able to load a x,y,t cube then use the mean intensity at each pixel as a background.

**Comment by FLIMinator** [comment]
Yes, when I tried to do this I was assuming my background was constant with time i.e. camera read noise/dark current. I think it's important to be able to make an average image from an ome.tiff stack in the same way that you can load a folder of background images to average and smooth. At the time of trying to do this, when using the platereader acquisition software that outputs only ome.tiffs, I had no idea how to get the images out of the stack to make an average image. Perhaps this is a problem for the platereadrer software i.e. other users not in our group are not using ome.tiff stacks that are not easy to interpret. Perhaps I'm missing something, I'd be happy to be persuaded this is not a problem.

**Comment by seanwarren** [comment]
Yes I agree (although it’s a slightly separate issue)

**Comment by imunro** [comment]
In that case, I will add this capability just as soon as I can.

**Comment by imunro** [comment]
This functionality added by commit c179a96. 
One caveat. I have followed the functionality of the tif-stack equivalent i.e. averaging in time then median filtering the (double) result. My instinct would have been to median filter the uint16 planes and then average.  I'm assuming @seanwarren has looked at this.

**Comment by seanwarren** [comment]
Statistically it's better to average first and then apply the median filter, otherwise you lose information. Its also (much) quicker.

On 8 Feb 2015 14:15, imunro <notifications@github.com> wrote:

This functionality added by commit c179a96<https://github.com/openmicroscopy/Imperial-FLIMfit/commit/c179a9679b13a3ea7b926c597f51c2f7cd4e6d3a>.
One caveat. I have followed the functionality of the tif-stack equivalent i.e. averaging in time then median filtering the (double) result. My instinct would have been to median filter the uint16 planes and then average. I'm assuming @seanwarren<https://github.com/seanwarren> has looked at this.

**Comment by imunro** [comment]
In that case - closing.

**Comment by imunro** [comment]
@FLIMinator  Hugh do you have a test ome-tiff that I could look at?

**Comment by FLIMinator** [comment]
Hi Ian,

Z:\User Lab Data\Ian Munro\Hugh ome.tiff background test

Regards,

Hugh

**Comment by imunro** [comment]
Thanks Hugh

Ian


On 9 Feb 2015, at 23:43, FLIMinator <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Ian,

Z:\User Lab Data\Ian Munro\Hugh ome.tiff background test

Regards,

Hugh

**Comment by imunro** [comment]
Thanks Hugh. Assuming that the test files that you gave me are backgrounds then they do appear to be time-resolved 1600 - 11400ps so my code should hopefully be fine.

**Comment by FLIMinator** [comment]
OK, you tried it and it worked?

Regards,

Hugh

**Comment by imunro** [comment]
Haven't had a chance yet. I  just checked that this was a standard FLIM 0me-tiff i.e. time-resolved like the ones I have tested with.
