### ISSUE TITLE
when creating time varying background default offset is confusing when using ome.tiffs

### ISSUE THREAD

**Issue by FLIMinator** [openmicroscopy/Imperial-FLIMfit#118]
When I create a time varying background using ome.tiffs I first change the default background value of 200 to 0 and then click the create time varying background option. 

When I load the tvb xml file into my data the tvb is offset by 200 points i.e. oversubtracted by  200. 

To make a tvb work I have to instead set the defaul background value -200 before creating the tvb. 
 
Perhaps I'm doing something wrong?

**Comment by seanwarren** [comment]
Hi Hugh,

You should set the camera background to the correct level (not zero) when making a TVB map
Ideally you should load a camera background image

Cheers
Sean
