### ISSUE TITLE
Add "Time-averaged background from a time-resolved image" functionality to OMERO menu

### ISSUE THREAD

**Issue by imunro** [openmicroscopy/Imperial-FLIMfit#120]
See https://github.com/openmicroscopy/Imperial-FLIMfit/issues/116# for file-side.

**Comment by seanwarren** [comment]
Just for clarification the background image stacks aren’t time resolved as such – they’re just multiple repeats

**Comment by imunro** [comment]
Ah! If the time-resolved annotation is absent from the file then my code won't work. Depends what Doug has done when creating the files.

**Comment by imunro** [comment]
Addressed by commit c2bd97
