### ISSUE TITLE
 loading 3X3 binning by mistake

### ISSUE THREAD

**Issue by elizabethnoble0714** [openmicroscopy/Imperial-FLIMfit#125]
The software loads the smoothening to 3x3 binning by default, leading to errors while trying to fit single pixel data(different values for fit selected decay and fit dataset).

**Comment by seanwarren** [comment]
We need to test for single pixel datasets when fitting single points

**Comment by imunro** [comment]
Seems like we should set the binning to Off if the loaded image is small. Say < 9 in x or y ?

**Comment by seanwarren** [comment]
Maybe better to have an exception for 1x1 images

On 5 Mar 2015, at 10:02, imunro <notifications@github.com<mailto:notifications@github.com>> wrote:


Seems like we should set the binning to Off if the loaded image is small. Say < 9 in x or y ?

**Comment by imunro** [comment]
Ok an arbitrary threshold perhaps isn't a good idea but won't we then have the same issue for -say 2x2 images?

**Comment by imunro** [comment]
Addressed by above commit.
