### ISSUE TITLE
Defaultly loading only the first channel of multichannel single pixel data

### ISSUE THREAD

**Issue by elizabethnoble0714** [openmicroscopy/Imperial-FLIMfit#126]
While trying to open a multiple channel TCSPC data for an emission scan, the latest updated software loads the first channel by default. In the previous versions the software detected the channels and there was an option to select, either load all the channels or just one from a  pop-up menu.

Could this be related to fixing the problem related to loading time-varying background?

**Comment by imunro** [comment]
For multi-channel (or any multi-plane) data you should get a pop-up asking you to select a plane
If there is only one channel in the data this will not appear.

**Comment by elizabethnoble0714** [comment]
The latest update fails to do so

**Comment by imunro** [comment]
Could you send me the file in question please.

**Comment by elizabethnoble0714** [comment]
Sure. Attaching it along

Regards,
Elizabeth

**Comment by seanwarren** [comment]
Fixed in commit 854c50ebc8a95513734722e011265231c8637a95

**Comment by seanwarren** [comment]
This was related to a previous botched fix to load malformed cuvette data
