### ISSUE TITLE
Name of Fit results OMERO Dataset needs to be shorter

### ISSUE THREAD

**Issue by imunro** [openmicroscopy/Imperial-FLIMfit#127]
As reported by @pwalczysko during pre-release testing of 4.8.0.

" - after "Export fitting results" the text in the popup "The analysis dataset..." is not very legible (or maybe it is just the name of the fitting dataset is too complicated to understand). Maybe in the wording it could be stated that here the Dataset is an OMERO Dataset, and that the analysis results have been attached to it as a result ? (will be hard to squeeze into the box, but then, see above, the name of the dataset should be shorter and better thought out)"

**Comment by imunro** [comment]
As a first step I have amended the description field of the new Dataset to read as follows:

![screen shot 2015-03-09 at 14 02 19](https://cloud.githubusercontent.com/assets/1183110/6556379/099f3592-c665-11e4-9b9c-6add05a6ba0a.png)
 @yalexand Do you think it would now be ok to omit the date/time form the Dataset name ?

**Comment by yalexand** [comment]
can do certainly, - if there are multiple analyses, they will look exactly the same in Insight etc. it was the only reason I attached it there, to distinguish between consequtive analyses

**Comment by imunro** [comment]
Hmmm makes sense.

**Comment by imunro** [comment]
As of 4.9.0 the user now has control of where fitting results are placed.
