### ISSUE TITLE
SV IRF not working

### ISSUE THREAD

**Issue by FLIMinator** [openmicroscopy/Imperial-FLIMfit#129]
SV IRF does not seem to work in the newest version, 4.8.
SV IRF does not work in previous versions.

**Comment by seanwarren** [comment]
More information please hugh ☺
Cheers
Sean

**Comment by FLIMinator** [comment]
Hey Sean,

Using 4.8, using an ome.tif file format, using 1 field of view loaded, load a scatter irf ome.tiff. The IRF size is quite large, 2x2 binning and 100s of images. I use load spatially varying IRF option on file tab. See below for example profile of IRF in ss. 

also see below example of errors.  Errors depend on what was loaded at same time e.g. tvb and dc offset image and if data was thresholded. The first error line seems to be same each time. The software freezes or doesnt depending on settings before loading IRF.

![spatialyl varying irf error 4 8 3](https://cloud.githubusercontent.com/assets/7783135/7092155/571fc2a4-dfa7-11e4-8a32-6e494b076ca3.png)

![spatialyl varying irf error 4 8](https://cloud.githubusercontent.com/assets/7783135/7092222/c7ced490-dfa7-11e4-8ca3-5afdab07bfd5.png)

![spatialyl varying irf error 4 8 2](https://cloud.githubusercontent.com/assets/7783135/7091994/18d0dc32-dfa6-11e4-9386-b3d75e338187.png)

**Comment by imunro** [comment]
I can look at this when I get back on Tue.
________________________________________

**Comment by imunro** [comment]
I've just been trying and failing to replicate the issue reported where FLIMfit fails to load the SV irf.
I seem to be able to load Hugh's irf  image without problem (on a mac)  and the displayed irf does seem to change slightly as I click around the image - which looks promising.
OTOH changing the Mode from 'Integrated Intensity' to 'SV irf" displays a white square! - did this ever work @seanwarren ? More seriously, attempting a global fit crashes Matlab!  Slightly stumped here.

**Comment by imunro** [comment]
I've attempted to add some code to display the SV IRF when that mode is selected.
Which seems to work for loading a non-xml sv irf.
I'm displaying the member  data_series.image_irf 
When I load  the file  "sv irf map.xml" from Hugh's test data as a sv irf this field remains empty as does the display.
Looking at the .xml in this file I see t_irf, irf and t0_image.   So I see 2 possibilities either I am displaying the wrong field @seanwarren  or I'm loading the wrong file @FLIMinator ?

**Comment by seanwarren** [comment]
That's a sv IRF

On 2 May 2015 01:35, imunro <notifications@github.com> wrote:

I've attempted to add some code to display the SV IRF when that mode is selected.
Which seems to work for loading a non-xml sv irf.
I'm displaying the member data_series.image_irf
When I load the file "sv irf map.xml" from Hugh's test data as a sv irf this field remains empty as does the display.
Looking at the .xml in this file I see t_irf, irf and t0_image. So I see 2 possibilities either I am displaying the wrong field @seanwarren<https://github.com/seanwarren> or I'm loading the wrong file @FLIMinator<https://github.com/FLIMinator> ?

**Comment by imunro** [comment]
So loading a dv irf should set the t0 image ?

**Comment by seanwarren** [comment]
If it is a XML file containing a single IRF and a shift map then yes.
If (less commonly, but sometimes used by Hugh) it’s a full spatially varying IRF (i.e. a full decay for each pixel) then no

**Comment by FLIMinator** [comment]
Hi Ian,

I'm discussing the load spatially varying irf option in FLIMfit. This does
not involved the XML file containing a single IRF. Instead it requires the
IRF measurement i.e. all the whole IRF stack of images.

Cheers,

Hugh

**Comment by imunro** [comment]
Ok got it now.I think Do I have an example of the data for which this is failing ? 
I strongly suspect this was another symptom of the genops/Anca bug but it would be nice to check.

**Comment by imunro** [comment]
I've tried loading one ome-tiff from fogim_datastore/User Lab Data/Ian Munro/Hughs segmentation testing folder/Sequenced FLIM acquisition 2015-03-19_16.36.09 as data and then a second as a SV_irf.
You can now see the sv-irf by changing the display mode(which is good)  but I still can't find any problems. Maybe this was actually a different issue ?

**Comment by seanwarren** [comment]
Hi Ian, you also need to explicitly tell it to use the SV IRF in the advanced fitting options tab.

**Comment by imunro** [comment]
Thanks Sean but I wouldn't expect a successful fit using a randomly chased  FOV as an IRF so I don't think I can  test more than that the sv irf is loaded until I get valid data.

**Comment by FLIMinator** [comment]
Hi Ian, 

Just load the dye plate data I gave you or use any of the data I gave you.

Cheers, 

Hugh


Sent from Samsung Mobile

-------- Original message --------

**Comment by imunro** [comment]
ok Hugh. I've loaded the data from /fogim_datastore/User Lab Data/Ian Munro/2015 platereader data/plate/Unknown , loaded the file  /fogim_datastore/User Lab Data/Ian Munro/2015 platereader data/scatter irf/2015-02-03_10.16.48_FLIMSnap.ome.tiff as a SV IRF, set the Integrated min to 800 and fit a double both globally and pix-by-pix all on t6 and all without problem. Can we call this fixed ?

**Comment by imunro** [comment]
Hang on! One more thing I forgot to test?

**Comment by imunro** [comment]
Still no problems apart from the usual windows "Warning:File not found"
Can I close this one?

**Comment by FLIMinator** [comment]
Thanks Ian sounds like its working!

I presume code had to be changed and it didn't just start working?

Best,

Hugh


Sent from Samsung Mobile

-------- Original message --------

**Comment by imunro** [comment]
Hi Hugh. It's likely that it was fixed when we fixed the Anca/genops bug ( that's certainly what the error message above looks like) but I've never  been able to work out how to make it go wrong - your description says "Errors depend on what was loaded at same time e.g. tvb and dc offset image and if data was thresholded." and I wasn't sure what data you were using.

**Comment by FLIMinator** [comment]
Thanks Ian!
