### ISSUE TITLE
Pixel by Pixel fitting on terminalsix prohibitively slow.

### ISSUE THREAD

**Issue by imunro** [openmicroscopy/Imperial-FLIMfit#135]
As reported by A.Margineanu.  Processing the data following the steps below - is prohibitively slow.
The progress bar reached 4% after 2 hours before I gave up (running from Source in Matlab) although processing was continuing without errors.

NB Attempting this on my (Mac) laptop it appeared to reach 36% in around 30 mins before hanging but this has yet to be confirmed using exactly the described steps.

-	Load raw data file: 
o	(Fogim_datastore) Z:\Our Projects\RASSF plates\Sectioned plate 2014\Anca\sectioned plate all new.raw
-	Load ‘Time point calibration file’:
o	Z:\Our Projects\RASSF plates\Sectioned plate 2014\Anca\CalibrationData\fast delay 60MHz CAL80MHz-3.csv
-	Load IRF (not ‘Spatially varying IRF’)
o	Z:\Our Projects\RASSF plates\Sectioned plate 2014\Anca\CalibrationData\library irf.xml
-	Load ‘Time varying background’:
o	Z:\Our Projects\RASSF plates\Sectioned plate 2014\Anca\tvb computed.xml
-	Import plate metadata:
o	Z:\Our Projects\RASSF plates\Sectioned plate 2014\Anca\t0 sectioned last.csv
-	Load Acceptor images – Import saved acceptor images:
o	Z:\Our Projects\RASSF plates\Sectioned plate 2014\Anca\AcceptorImagesFullPlate.tiff
-	Segmentation manager – Load segmentation images:
o	Z:\Our Projects\RASSF plates\Sectioned plate 2014\Anca\segmentation images no A threshod
o	Select options – Replace & “ONLY FOV”
-	Import exclusion list:
o	Z:\Our Projects\RASSF plates\Sectioned plate 2014\Anca\bad fov sectioned 800 threshold.txt
-	Settings: 
o	Smoothing 5x5
o	Integrated min 800
o	Time min 0
o	Counts/Photon 1
o	Rep rate 60
o	Gate max 2e+04
o	Time max 2e+04
o	Background – TV Image (960)
o	IRF – Scatter, Background 0, Time min 1300, Time max 4800, IRF shift (-210)
o	Advanced – Use FOV IRF shift
o	Global fitting – Pixel wise
o	No. Exp 1
o	No. fixed 0
o	Fit contributions – Fitted locally
o	Fit IRF shift - Fixed
o	Automatically estimate lifetimes – checked (Initial tau 2000)

**Comment by imunro** [comment]
I just repeated the same set of steps with the same data (from Matlab) on my laptop without problem in about 80 mins. Not sure what this tells me as the .dll equivalent might be well out of data & I'm equally unsure which .dll is being used on terminal six. I'll check tomorrow.

**Comment by seanwarren** [comment]
Is the library compiled using Debug on the source version on T6?

**Comment by imunro** [comment]
Good question. I have realised that I have no idea what .dll is being used from matlab as I cloned the repo but didn't build the .cpp. Would it just pick up the installed one? I hope not as there are now 3 FLIMfit's on t6.  I'll have a look shortly.

**Comment by seanwarren** [comment]
No it won’t pick up the installed one – there is a dll in the repo which should be up to date but may well (probably will) be a debug version

**Comment by imunro** [comment]
I'll try with the built version again then as soon as I get to the office.

**Comment by imunro** [comment]
Trying exactly the same sequence of commands on t6 with the installed 4.8.0 build (i.e. MCR) gives the following error when switching Background to to 'TV Image' after loading.  Going to try now from Matlab with the .dll from the build.

**Comment by imunro** [comment]
Running from Matlab Source on t6 with the build version of the .dll I achieved a successful fit in ~15 mins.  Bug appears to be definitely in the matlab front end. So closing this issue and opening a new one
