### ISSUE TITLE
Cannot seem to load single trace IRF in 4.8

### ISSUE THREAD

**Issue by FLIMinator** [openmicroscopy/Imperial-FLIMfit#136]
I have a typical IRF trace, column 1 has time, column 2 has intensity. It works with version 4.7 and earlier versions.

![image](https://cloud.githubusercontent.com/assets/7783135/7337405/68987dd4-ec20-11e4-8859-abec916c2188.png)

**Comment by imunro** [comment]
If this is a .csv file then a fix is already in place for 4.8..1 ?

**Comment by FLIMinator** [comment]
Yes is it a csv file. Does it work if it is another format?

**Comment by imunro** [comment]
As far as I know it should. I'm hoping to get a 4.8.1 out with this fix in fairly quickly as it's a bit embarrassing.

**Comment by imunro** [comment]
Closing this one as AFAIK it's fixed for the next release.
