### ISSUE TITLE
Out of computer memory?

### ISSUE THREAD

**Issue by FLIMinator** [openmicroscopy/Imperial-FLIMfit#137]
I load a finely sampled dye measurement which is a large 40 Mb ome.tiff.ome image and load an irf shift map and 4.8/terminalsix cannot fit the data apparently because of memory issues.

![image](https://cloud.githubusercontent.com/assets/7783135/7346242/3a8dc246-ecd4-11e4-8ed3-c7c53040aa90.png)

**Comment by FLIMinator** [comment]
Works with another computer. Must be something wrong with terminalsix. Has memory management be changed in the last few days for terminalsix??

**Comment by FLIMinator** [comment]
I have re-opened this issue because we (Ian and I) cannot figure out why there is a memory issue?

Could the cause of this issue be cropping up elsewhere also.

**Comment by imunro** [comment]
Possibly a side-defect of the genops bug ??? Going to close for now please re-open if it happens with 4.8.1 (Release version)
