### ISSUE TITLE
tvb switching  issue in 4.8.0 on t6 (see https://github.com/openmicroscopy/Imperial-FLIMfit/issues/135)

### ISSUE THREAD

**Issue by imunro** [openmicroscopy/Imperial-FLIMfit#138]
Using the steps and data described in https://github.com/openmicroscopy/Imperial-FLIMfit/issues/135  we see the error below on switching Background to 'TV Image' 

Seems likely that I have x/y transposed when loading a tvb background but I need to find why this manifests only in the build not the current Matlab source.

![screen shot 2015-04-27 at 11 42 36](https://cloud.githubusercontent.com/assets/1183110/7346944/48ff421c-ecdb-11e4-88ed-6189cb30297b.png)

**Comment by imunro** [comment]
I've been debugging https://github.com/openmicroscopy/Imperial-FLIMfit/blob/master/FLIMfitFrontEnd/Classes/%40flim_data_series/flim_data_series.m line 578
bg = bg .* obj.tvb_profile + obj.background_value;

 and I find the following: size(bg) (after reshape) == 1,1,512,672  size(obj.tvb_profile) == 6,1 
IIRC a lot of maths depends on versions of * which handle different size arrays.
If this is no longer being built for the PC version (i.e. the Matlab defaults are being used) would it explain this bug and why I can't reproduce from source?
@seanwarren can you remind me where they gets set up and built please ?

**Comment by seanwarren** [comment]
Yes, you need to call genmakeops. Also need to make sure that the compiled mex files are included in the compiled version.

**Comment by imunro** [comment]
If I'm right then including in the deployed version was the problem. Just trying to check that now. Don't suppose you know how to include paths with spaces in mcc ?

**Comment by seanwarren** [comment]
Not off the top of my head – might be easier to remove the space in the path!

**Comment by imunro** [comment]
Thanks. That's Plan B :-)

**Comment by imunro** [comment]
I've added  -a HelperFunctions/doubleops_PCWIN64/@double/*  to the mcc command in compile.m  but I'm still getting the same problem. However, It tests if genops is working in add path_globalanalysis & if it isn't tries to build it locally so I'm guessing this doesn't work either. Just trying to debug that now but any thoughts welcome.

**Comment by imunro** [comment]
Ok so addpath_global...  isn't called in the deployed code. Do you think it's possible that genops isn;t switched on ?? Seems to be switched on by calling genops(1)

**Comment by imunro** [comment]
I have now confirmed that genops isn't working in the deployed versions. I've  tried several different ways to include HelperFunctions/doublops_PCWIN64 in the deployed package but none seem to work.
Any thoughts @seanwarren I'm running out of ideas.

**Comment by imunro** [comment]
You're clearly away or busy but just to keep you up to date .. As this seems to be an issue with either mcc or it's documentation I've dropped this on the Matlab help desk for now.
I do have an alternative soln though. See http://www.lce.hut.fi/~ave/code/genopsm/  for  (more recent) .m implementations of the genops functions. Depending on how many places in the code you depend on the extra genops functionality ? ( I'm guessing not many as this bug has been so hard to replicate) then we could just replace the relevant call to '.*' or whatever with the appropriate matlab function. This would certainly work for this bug.

**Comment by seanwarren** [comment]
Hi Ian, OK sounds good - I don't think there are many places that depend on it, and where it does we can probably use bsxfcn or this version instead. However we should have a check through the code to see where is calling genops first - I'm afraid I'm not sure of the top of my head.

**Comment by imunro** [comment]
Hi Sean That's the  tricky bit I think because genops overloads the '.*' operator among others I don't really know how to spot where the standard matlab operators don't give the answer that you are expecting.

**Comment by seanwarren** [comment]
Hi Ian, I suggest that we modify the genops code so that it throws an error with mexErrMsgTxt when called. If we run through some standard workflows we should hit on any code that relies on genops pretty quickly. I'll make a commit like this now, are you ok to test it later today?

**Comment by imunro** [comment]
Sure. Can do

Watch out though I left some debug statements lying about in the last couple of commits.
Won’t your message get called on every call to .* though? Or does genops only get called if the inputs are invalid ?

Ian


On 29 Apr 2015, at 12:41, Sean Warren <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Ian, I suggest that we modify the genops code so that it throws an error with mexErrMsgTxt when called. If we run through some standard workflows we should hit on any code that relies on genops pretty quickly. I'll make a commit like this now, are you ok to test it later today?

**Comment by seanwarren** [comment]
We'll find out :) I'll give it a test tomorrow Oz time as well, we might need to only throw that error in certain cases

On 29 Apr 2015 21:47, imunro <notifications@github.com> wrote:
Sure. Can do

Watch out though I left some debug statements lying about in the last couple of commits.
Won’t your message get called on every call to .* though? Or does genops only get called if the inputs are invalid ?

Ian


On 29 Apr 2015, at 12:41, Sean Warren <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Ian, I suggest that we modify the genops code so that it throws an error with mexErrMsgTxt when called. If we run through some standard workflows we should hit on any code that relies on genops pretty quickly. I'll make a commit like this now, are you ok to test it later today?

**Comment by imunro** [comment]
I have shifted your debug line to what looks like the right place to show only when the built-in functions aren't called (fingers crossed) This does throw an error at the line where we already know there is a problem in the deployed version so it look promising.
