### ISSUE TITLE
Global fitting fails when empty "images" present

### ISSUE THREAD

**Issue by yalexand** [openmicroscopy/Imperial-FLIMfit#142]
That was discovered for the case of reconstructed OPT-FLIM data loaded from XYZ+lifetime OME.tiff.

The commit [6 Feb 2015 17:36 3d1c1d0] fixes that for the case of pixelwise fitting, but Global just hangs.
If one excludes these empty planes from the input data either on loading, or on sending to dll, - Global works normally.

**Comment by imunro** [comment]
I fear this one's for you @seanwarren

**Comment by imunro** [comment]
I’m going to remove his mornings Nan Inf debug now as it wasn’t that.

Ian


On 28 May 2015, at 13:29, yalexand <notifications@github.com<mailto:notifications@github.com>> wrote:


That was discovered for the case of reconstructed OPT-FLIM data loaded from XYZ+lifetime OME.tiff.

The commit [6 Feb 2015 17:36 3d1c1d0<https://github.com/openmicroscopy/Imperial-FLIMfit/commit/3d1c1d0de96c61999e69ac6bf5c1270f09eb22b2>] fixes that for the case of pixelwise fitting, but Global just hangs.
If one excludes these empty planes from the input data either on loading, or on sending to dll, - Global works normally.

**Comment by imunro** [comment]
Fixed AFAIK in 4.9.0  @seanwarren ?

**Comment by imunro** [comment]
Fixed AFAIK in 4.9.0
