### ISSUE TITLE
segmentation improvement: to add filtering segmented objects by shape factor

### ISSUE THREAD

**Issue by yalexand** [openmicroscopy/Imperial-FLIMfit#148]
in well plates, round cells are physiologically different & show different lifetimes, so it is better to have control

**Comment by imunro** [comment]
I thought you just fixed this ?

**Comment by yalexand** [comment]
It was next request from George Chennell, to have both min and max thresholds on shape factor.
Added just now.

Cheers,
Y.

**Comment by imunro** [comment]
Merged in 4.9.1
