### ISSUE TITLE
Max Display in Integrated Intensity changes with Integrated Min

### ISSUE THREAD

**Issue by imunro** [openmicroscopy/Imperial-FLIMfit#154]
The no displayed at top-right of the integrated intensity window seems to change as you change the Integrated Min control. @seanwarren Can you just confirm this is a bug not a feature please before I try to fix it.

**Comment by imunro** [comment]
Sorry I should have checked the code before reporting . This clearly isn't the max in the image, as I expected, but the max used for the colour map - determined by a percentile.  
So it looks as if the problem might be that this goes haywire once you have thresholded out all or all but one of the pixels.

**Comment by seanwarren** [comment]
Hi Ian,

I guess this isn’t exactly intended, but I don’t think it’s a practical issue.

Cheers
Sean

On 4 Aug 2015, at 03:10, imunro <notifications@github.com<mailto:notifications@github.com>> wrote:


Sorry I should have checked the code before reporting . This clearly isn't the max in the image, as I expected, but the max used for the colour map - determined by a percentile.

So it looks as if the problem might be that this goes haywire once you have thresholded out all or all but one of the pixels.

**Comment by imunro** [comment]
After further investigation it looks as if FLIMfit is behaving perfectly. The data contains a tiny handful of very bright pixels which are excluded from the autoscaling. As you push up the min threshold these start  to be included in the colour map  so the displayed max goes up. I'm thinking that displaying a real data max might help spot this sort of behaviour.

**Comment by imunro** [comment]
Max intensity display now added.
