### ISSUE TITLE
Error loading data after exiting segmentation controller.

### ISSUE THREAD

**Issue by imunro** [openmicroscopy/Imperial-FLIMfit#155]
After opening the segmentation controller I segmented an image and then closed the segmentation window using the red cross at top-left rather than the ok button.

Subsequent attempts to load data then gave me:

Warning: Error occurred while executing callback:
Invalid or deleted object.

Error in flim_data_series_observer/data_update_evt (line 60)
            if ~ishandle(obj.data_series) && obj.data_series.init

Error in flim_data_series_observer>@(varargin)obj.data_update_evt(varargin{:}) (line 52)
            obj.ds_lh = addlistener(obj.data_series,'data_updated',@obj.data_update_evt);

Error in flim_data_series/clear (line 947)
                notify(obj,'data_updated');

Error in front_end_menu_controller/menu_file_load_single_callback (line 586)
                obj.data_series_controller.data_series.clear();

Error in front_end_menu_controller/set_callbacks/@(varargin)obj.menu_file_load_single_callback(varargin{:})

> In flim_data_series.flim_data_series>flim_data_series.clear at 947
  In front_end_menu_controller>front_end_menu_controller.menu_file_load_single_callback at 586
  In front_end_menu_controller>@(varargin)obj.menu_file_load_single_callback(varargin{:}) 

Any thoughts @yalexand ? It looks as if something is being created that isn't deleted if you exit this way.

**Comment by yalexand** [comment]
No unfortunately didn’t see this before.. GUIDE sometimes behave strangely

**Comment by imunro** [comment]
Fixed in 4.9.1
