### ISSUE TITLE
Problems with exporting coloured histogram to .ppt (windows only)

### ISSUE THREAD

**Issue by seanwarren** [openmicroscopy/Imperial-FLIMfit#31]
When r-clicking on a coloured histogram under windows the displayed image is a rainbow rectangle (until re-sized ??).

**Note**: This issue has been automatically migrated from Bitbucket
Created by @imunro on 2013-07-02 12:32:44+00:00

**Comment by imunro** [comment]
All the .ppt options were lost during the Matlab 2014b conversion so no longer applicable after 4.8
