### ISSUE TITLE
Can't open FLIM data from Leica Stellaris 8

### ISSUE THREAD

**Issue by jrwconway123** [openmicroscopy/Imperial-FLIMfit#376]
Hi, 

I am using a Leica Stellaris 8 FALCON to collect some FLIM data that I would like to analyse with FLIMfit, but I can't find a way to get the data to import into FLIMfit. If I export from LAS X as ome.tiff or try to open the .lif file directly, I get the error "Unable to load! Not time resolved data." Is there a way to export data from LAS X that can be opened in FLIMfit, or do I just need to stick with the Leica software? 

Thanks for any help/advice in advance, 
James

**Comment by AndreZeug** [comment]
Hi James, 
did you solve your problem?
I am using a FALCON on a SP8 and also have dificulties importing FLIM data to Matlab.
Any suggestion is welcome.

Thanks 
Andre

**Comment by jrwconway123** [comment]
Hi Andre,

We sort of solved the problem. Our Leica application specialist said that we should be able to export as .ptu files and then we could use those to import into other software. However, when we tried to do this we couldn't find that option in our version of LAS X. It's in the manual though, so I think that we should be able to get it back with an update. Maybe you can check if you have that option, and if not, ask Leica?

Hopefully they will sort this soon. 

All the best,
James

**Comment by AndreZeug** [comment]
Hi James,
surely we exported Leica data as '.ptu'. Still there are some differences to standard PicoQuant ptu files.
Sean, the developer of FLIMfit, helped us with correcting ptu import to Matlab. 

However there are 'some' remaining issues, especially at higher count rates. To get an idea, please have a look:
![grafik](https://user-images.githubusercontent.com/20279594/127617711-59dd7d7a-58b0-408a-8cde-9cd489172952.png)

For detailed information please contact me directly (zeug.andre@mh-hannover.de).

Best

Andre
