### ISSUE TITLE
Save as -> matlab fig

### ISSUE THREAD

**Issue by seanwarren** [openmicroscopy/Imperial-FLIMfit#49]
Attempting to save a matlab figure via a r-click & te 'save as" menu 
generates the following:

confirmed on mac & Win64

Warning: Unknown option in argument: 'fig'. 
> In savefig at 214
  In abstract_display_controller>abstract_display_controller.save_as at 132
  In abstract_display_controller>@(~,~,~)obj.save_as() at 70 
Error using savefig (line 222)
No output format given.

Error in abstract_display_controller/save_as (line 132)
                        savefig([pathname filesep name ' '
                        param_name],f,ext);

Error in abstract_display_controller>@(~,~,~)obj.save_as() (line 70)
                @(~,~,~) obj.save_as() );
 
Error while evaluating uimenu Callback

**Note**: This issue has been automatically migrated from Bitbucket
Created by @imunro on 2013-08-08 17:09:07+00:00, last updated: 2013-08-08 17:19:16+00:00

**Comment by imunro** [comment]
Fixed as part of the 2014b graphics upgrades.
