### ISSUE TITLE
Fit fails to complete

### ISSUE THREAD

**Issue by dougkelly88** [openmicroscopy/Imperial-FLIMfit#82]
Fitting pixelwise stalls when encountering a FOV in which all pixels are thresholded out. No error message returned. Also, doesn't appear to be in all cases in which images are completely thresholded out - in example attached, im_group 104 and 105 were thresholded out, but so was (for example) im_group 91. 

In case where only row A is selected, pixelwise gets to 26%, corresponding to im_group ~106. 

By contrast, imagewise fit gets to 99% before failing to terminate, see second example attached. 

Data is on SSD: G:\Doug raw\Full Plate RAW.raw

Issue present in both 4.7.0 and 4.6.2

![image](https://cloud.githubusercontent.com/assets/3948976/3762822/34f42a0e-189b-11e4-9404-f721fe8c398d.png)

![image](https://cloud.githubusercontent.com/assets/3948976/3762887/217950fc-189c-11e4-9de2-190e48a518ad.png)

**Comment by seanwarren** [comment]
Fixed in commit 3d1c1d0
